### ISSUE TITLE
In the discrete logarithm, allow one to supply his/her own modulus factorization.

### ISSUE THREAD

**Issue by ytrezq** [alpertron/calculators#29]
I know you calculator isn’t about being efficient, but your ᴇᴄᴍ step takes much time and doesn’t use worker thread for multrithreading.

Would it be possible to let users supplying their own factorization of the modulus that they would had obtained using a mix of ɴꜰꜱ/ᴇᴄᴍ outside your calculator ?

**Comment by alpertron** [comment]
Thanks for your comment.

The change to do what you propose is not difficult. The problem is that I'm using a slow method (Pohlig-Hellman) for computing the discrete logarithm. So, the bottleneck would be the actual computation of the discrete logarithm.

Notice that ECM is a sub-exponential method to factor the modulus, and Pohlig-Hellman is an exponential method to find the discrete logarithm.

**Comment by ytrezq** [comment]
I don t call pohlig Hellman slow. Pohlig Hellman is definitely faster is a 30Kb long number can be trivially factored through ecm.

**Comment by alpertron** [comment]
Please show me an example where the group factoring using ECM is slower than Pohlig Hellman.
